# Generated by Django 4.0.6 on 2022-09-23 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="uploaded_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
