version: "3"

services:
  api:
    image: "${ANNOTATOR_IMAGE_NAME_FULL_API}:latest-${ANNOTATOR_DEPLOYMENT_ENVIRONMENT}"
    volumes: 
      - api_static:/home/api/backend/static
      - api_media:/home/api/backend/media
      - api_db:/home/api/backend/db
    expose:
      - 8000
    environment:
      - DJANGO_DEBUG=${ANNOTATOR_BACKEND_DEBUG}
      - DJANGO_SECRET_KEY=${ANNOTATOR_BACKEND_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${ANNOTATOR_BACKEND_ALLOWED_HOSTS}
      - DJANGO_SUPERUSER_USERNAME=${ANNOTATOR_BACKEND_SU_NAME}
      - DJANGO_SUPERUSER_EMAIL=${ANNOTATOR_BACKEND_SU_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${ANNOTATOR_BACKEND_SU_PASSWORD}
      - DJANGO_USE_SSL=false
    restart: unless-stopped
  static:
    image: "${ANNOTATOR_IMAGE_NAME_FULL_STATIC}:latest-${ANNOTATOR_DEPLOYMENT_ENVIRONMENT}"
    volumes:
      - api_static:/home/api_static
    ports:
      - 80:80
    depends_on:
      - api
    restart: unless-stopped

volumes:
  api_static:
  api_media:
  api_db:
