# File for storing/editing constants

# Model constants

USER_USERNAME_MAX_LENGTH = 150
USER_EMAIL_MAX_LENGTH = 150

PROJECT_NAME_MAX_LENGTH = 100
PROJECT_DESCRIPTION_MAX_LENGTH = 255

MODELDATA_NAME_MAX_LENGTH = 100
MODELDATA_ANNOTATIONTYPE_MAX_LENGTH = 30
MODELDATA_MODELTYPE_MAX_LENGTH = 30

FILE_FILEPATH_MAX_LENGTH = 255
FILE_FILEFORMAT_MAX_LENGTH = 30
FILE_MAX_FILESIZE = 1000 * pow(2, 20)

LABEL_NAME_MAX_LENGTH = 100

# other constants

INTEGER_MAX = 0x7FFFFFFF
INTEGER_MIN = -INTEGER_MAX - 1

# time a model is locked for a user in seconds
LOCKING_TIME = 3600
