server {

  listen 80;

  client_max_body_size 0;

  add_header Cross-Origin-Opener-Policy "same-origin" always;
  add_header Cross-Origin-Embedder-Policy "require-corp" always;

  location / {
    root   /home/frontend;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /assets {
    root /home/frontend;
    add_header Cache-Control "public";
    expires 1y;

	add_header Cross-Origin-Opener-Policy "same-origin" always;
    add_header Cross-Origin-Embedder-Policy "require-corp" always;
  }

  location /api/static {
    alias /home/api_static/;
  }

  error_page 500 502 503 504 /50x.html;

  location = /50x.html {
      root /usr/share/nginx/html;
  }

}
